default:
  http_metas:
    content-type: text/html

  metas:
    title:        Atlantic Biomedical
    robots:       index, follow
    description:  Atlantic Biomedical
    keywords:     Atlantic Biomedical, medical, equipment, repair
    language:     en

  stylesheets:    [main, client, user, theme]

  javascripts:    []

  has_layout:     on
  layout:         layout
