<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/22 21:24:43

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root:d6Gxlk78T3@localhost/db142237_atlbiomedprod',
), 'sessions_db');
$this->databases['sessions_db'] = $database;

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'host' => 'localhost',
  'database' => 'db142237_atlbiomedprod',
  'username' => 'root',
  'password' => 'd6Gxlk78T3',
), 'propel');
$this->databases['propel'] = $database;

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'host' => 'localhost',
  'database' => 'db142237_atlbiomedprod',
  'username' => 'root',
  'password' => 'd6Gxlk78T3',
), 'atlbio');
$this->databases['atlbio'] = $database;
