<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/22 21:24:43
sfConfig::add(array(
  'app_default_map_location' => '818 Oregon Avenue Linthicum MD 2109',
  'app_default_map_location_title' => 'Atlantic Biomedical',
  'app_site_images_url' => 'http://portal.atlanticbiomedical.com/images/',
  'app_google_maps_api_key' => 'ABQIAAAAH8eXa0M6ghDzYagwHY4v2hSIy_WAr7UwMnWXIzgcAQul7TtErhSWFvWS5hr8ADs9x3KcyKFHEIyaHQ',
));
