<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/22 21:24:43
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
