<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/06/11 14:35:44
sfConfig::add(array(
  'app_default_map_location' => '818 Oregon Avenue Linthicum MD 2109',
  'app_default_map_location_title' => 'Atlantic Biomedical',
  'app_site_images_url' => 'http://biomed.wootroot.me/images/',
  'app_google_maps_api_key' => 'AIzaSyBJhZuTYgvG5q65VgZLgtfbe44Q82Dpl0c',
));
