<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/06/11 14:38:28
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
