<?php
// auto-generated by sfViewConfigHandler
// date: 2012/06/18 04:17:59
$context  = $this->getContext();
$response = $context->getResponse();

if ($this->actionName.$this->viewName == 'generateReportSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'listDevicesSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'deviceIdChangedSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'getDevicesSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'generateReportSuccess')
{
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Atlantic Biomedical', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Atlantic Biomedical', false, false);
  $response->addMeta('keywords', 'Atlantic Biomedical, medical, equipment, repair', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('client', '', array ());
  $response->addStylesheet('user', '', array ());
  $response->addStylesheet('theme', '', array ());
  $response->addStylesheet('process', '', array ());
  $response->addJavascript('scriptaculous/lib/prototype');
  $response->addJavascript('process');
}
else if ($templateName.$this->viewName == 'listDevicesSuccess')
{
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Atlantic Biomedical', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Atlantic Biomedical', false, false);
  $response->addMeta('keywords', 'Atlantic Biomedical, medical, equipment, repair', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('client', '', array ());
  $response->addStylesheet('user', '', array ());
  $response->addStylesheet('theme', '', array ());
  $response->addStylesheet('process', '', array ());
  $response->addJavascript('scriptaculous/lib/prototype');
  $response->addJavascript('process');
}
else if ($templateName.$this->viewName == 'deviceIdChangedSuccess')
{
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Atlantic Biomedical', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Atlantic Biomedical', false, false);
  $response->addMeta('keywords', 'Atlantic Biomedical, medical, equipment, repair', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('client', '', array ());
  $response->addStylesheet('user', '', array ());
  $response->addStylesheet('theme', '', array ());
  $response->addStylesheet('process', '', array ());
  $response->addJavascript('scriptaculous/lib/prototype');
  $response->addJavascript('process');
}
else if ($templateName.$this->viewName == 'getDevicesSuccess')
{
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Atlantic Biomedical', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Atlantic Biomedical', false, false);
  $response->addMeta('keywords', 'Atlantic Biomedical, medical, equipment, repair', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('client', '', array ());
  $response->addStylesheet('user', '', array ());
  $response->addStylesheet('theme', '', array ());
  $response->addStylesheet('process', '', array ());
  $response->addJavascript('scriptaculous/lib/prototype');
  $response->addJavascript('process');
}
else
{
  if (!$context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Atlantic Biomedical', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Atlantic Biomedical', false, false);
  $response->addMeta('keywords', 'Atlantic Biomedical, medical, equipment, repair', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('client', '', array ());
  $response->addStylesheet('user', '', array ());
  $response->addStylesheet('theme', '', array ());
  $response->addStylesheet('process', '', array ());
  $response->addJavascript('scriptaculous/lib/prototype');
  $response->addJavascript('process');
}

